import type {SidebarsConfig} from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorial: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorial: [
    "introduction",
    "tutorial/install",
    {
      type: "category",
      label: "Usages",
      collapsed: false,
      link: {
        type: "generated-index",
        title: "How to use Flask SQLAlchemy Compat",
        slug: "/category/usages",
        description:
          "Simple guides for migrating to this compatible version of Flask SQLAlchemy.",
      },
      items: [
        "tutorial/usages/flask-sqlalchemy-lite",
        "tutorial/usages/flask-sqlalchemy",
      ],
    },
    {
      type: "category",
      label: "Examples",
      collapsed: true,
      link: {
        type: "generated-index",
        title: "Examples",
        slug: "/category/examples",
        description: "Explanations of the example codes.",
      },
      items: [
        "tutorial/examples/db-only",
        "tutorial/examples/flask-sqlalchemy-lite",
        "tutorial/examples/flask-sqlalchemy",
      ],
    },
    "license",
  ],

  apis: [
    "api-overview",
    {
      type: "category",
      label: "auto",
      collapsed: true,
      link: {
        type: "doc",
        id: "apis/auto/index",
      },
      items: [
        "apis/auto/get_flask_sqlalchemy_lite",
        "apis/auto/get_flask_sqlalchemy_lite_proxy_ver",
        "apis/auto/get_flask_sqlalchemy",
        "apis/auto/get_flask_sqlalchemy_proxy_ver",
      ],
    },
    {
      type: "category",
      label: "backdict",
      collapsed: true,
      link: {
        type: "doc",
        id: "apis/backdict/index",
      },
      items: ["apis/backdict/BackDict", "apis/backdict/BackDictView"],
    },
    {
      type: "category",
      label: "backends",
      collapsed: true,
      link: {
        type: "doc",
        id: "apis/backends/index",
      },
      items: [
        "apis/backends/ModulePlaceholder",
        "apis/backends/BackendProxy",
        "apis/backends/proxy",
        "apis/backends/conditional_import",
        "apis/backends/is_module_invalid",
      ],
    },
    {
      type: "category",
      label: "flask_sa_api",
      collapsed: true,
      link: {
        type: "doc",
        id: "apis/flask_sa_api/index",
      },
      items: [
        "apis/flask_sa_api/SQLAlchemyProxy",
        "apis/flask_sa_api/as_flask_sqlalchemy",
      ],
    },
    {
      type: "category",
      label: "flask_sa_lite_api",
      collapsed: true,
      link: {
        type: "doc",
        id: "apis/flask_sa_lite_api/index",
      },
      items: [
        "apis/flask_sa_lite_api/SQLAlchemyLiteProxy",
        "apis/flask_sa_lite_api/as_flask_sqlalchemy_lite",
      ],
    },
    {
      type: "category",
      label: "protocols",
      collapsed: true,
      link: {
        type: "doc",
        id: "apis/protocols/index",
      },
      items: [
        "apis/protocols/ModelProtocol",
        "apis/protocols/SQLAlchemySharedProtocol",
        "apis/protocols/SQLAlchemyLiteProtocol",
        "apis/protocols/SQLAlchemyProtocol",
      ],
    },
    {
      type: "category",
      label: "utilities",
      collapsed: true,
      link: {
        type: "doc",
        id: "apis/utilities/index",
      },
      items: [
        "apis/utilities/DBNotReadyError",
        "apis/utilities/hook_classmethod",
        "apis/utilities/hook_base_model",
        "apis/utilities/apply_to_engines",
        "apis/utilities/clone_method",
        "apis/utilities/clone_function",
        "apis/utilities/get_app_ctx_id",
        "apis/utilities/QueryGetter",
        "apis/utilities/TableNameGetter",
      ],
    },
  ],
};

export default sidebars;
